sources:
  - Sutasoma.glyphs
axisOrder:
  - GRAD
  - wght
  - ital
familyName: Sutasoma
stat:
  - name: Grade
    tag: GRAD
    values:
      - name: Display
        value: -100
      - name : Text
        value : 0
  - name: Weight
    tag: wght
    values:
      - name: ExtraLight
        value: 200
      - name: Light
        value: 300
      - name: Regular
        value: 400
        flags: 2
        linkedValue: 700
      - name: Medium
        value: 500
      - name: SemiBold
        value: 600
      - name: Bold
        value: 700
      - name: ExtraBold
        value: 800
  - name: Italic
    tag: ital
    values:
      - name: Text
        value: 0
        flags: 2
        linkedValue: 1
      - name: Display
        value: 0
        flags: 2
        linkedValue: 1
      - name: Italic
        value: 1

