sources:
  - Sutasoma.glyphs
axisOrder:
  - GRAD
  - wght
  - slnt
familyName: Sutasoma
stat:
  - name: Grade
    tag: GRAD
    values:
      - name: Normal
        value: 0
        flags: 2
  - name: Weight
    tag: wght
    values:
      - name: ExtraLight
        value: 200
      - name: Light
        value: 300
      - name: Regular
        value: 400
      - name: Medium
        value: 500
      - name: SemiBold
        value: 600
      - name: Bold
        value: 700
      - name: ExtraBold
        value: 800
  - name: Slant
    tag: slnt
    values:
      - name: Default
        value: 0
        flags: 2
        linkedValue: -9
      - name: Italic
        value: -9
